apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
  labels:
    app: django
    component: clearsessions
spec:
  schedule: "0 0 1 * *"
  startingDeadlineSeconds: 3600
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: clearsessions
            image: django_1:latest
            imagePullPolicy: Never
            command: ["python", "manage.py", "clearsessions"]
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: SECRET_KEY
            - name: DEBUG
              value: "False"
            - name: ALLOWED_HOSTS
              value: "star-burger.test,localhost,127.0.0.1"
          restartPolicy: Never
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3